"""Prompt 模板包。"""

from src.llm.prompts.templates import (
    DISCUSSION_PROMPT,
    EVALUATION_PROMPT,
    EXPERIMENT_DESIGN_PROMPT,
    FIGURE_PROMPT,
    LITERATURE_SEARCH_PROMPT,
    PAPER_SECTIONS,
    PAPER_WRITE_PROMPT,
    SUBMIT_PROMPT,
)

__all__ = [
    "DISCUSSION_PROMPT",
    "EVALUATION_PROMPT",
    "EXPERIMENT_DESIGN_PROMPT",
    "FIGURE_PROMPT",
    "LITERATURE_SEARCH_PROMPT",
    "PAPER_SECTIONS",
    "PAPER_WRITE_PROMPT",
    "SUBMIT_PROMPT",
]
